### ISSUE TITLE
请问如何关闭注册功能

### ISSUE THREAD

**Issue by youzhazhu** [chatgpt-web-dev/chatgpt-web#206]
如题，我想访客不用注册，直接使用ChatGPT。
我是用Docker Compose部署的，我的配置如下。
![image](https://github.com/Kerwin1202/chatgpt-web/assets/51223192/fc63bd0b-e8bf-490e-af21-08e65c926239)
已经将开始注册设置为false。

但是在网页端依旧提示要注册登录
![image](https://github.com/Kerwin1202/chatgpt-web/assets/51223192/4aab69f1-ed24-4133-bf8f-71bc8007dbfb)

BTW，关闭注册功能后怎么使用管理员后台。

**Comment by Kerwin1202** [comment]
关闭注册无法使用管理员后台，本项目倾向于要注册登录， 至于关闭登录，是另一个Secret 之类的字段
