### ISSUE TITLE
小白请问，有宝塔版的部署教程吗

### ISSUE THREAD

**Issue by immochan** [chatgpt-web-dev/chatgpt-web#224]
大家好，今天尝试了多次，打包完成后，上传到服务器进行访问，首页总是报500错误，使用另一个Issues中的大佬的一键脚本，也出现cp错误。小白不太懂docker，所以请问有没有大佬使用宝塔部署成功的，方便给个详细教程么，万分感谢~

**Comment by Kerwin1202** [comment]
宝塔 我也没试过，一般来说是不会呀，docker 安装这个没问题吧。然后下面这个文件下载，按照提示修改，然后保存 `docker-compose.yml` 服务器上 `docker-compose up -d` 运行 ，如果有问题，则 docker-compose logs 这样看下日志
https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml

**Comment by Dimp07** [comment]
https://www.cnblogs.com/guohaomeng/p/17259713.html可以仿照这个网站的
