### ISSUE TITLE
GPT4出来啦

### ISSUE THREAD

**Issue by wshze** [chatgpt-web-dev/chatgpt-web#297]
7月7日，OpenAI在官网宣布，GPT-4 API全面开放使用。现所有付费API用户都可直接访问8K上下文的GPT-4，无需任何等待和候补。

预计到7月底之前，OpenAI会向全新的开发人员开放GPT-4 API使用权限。

**Comment by huangwb8** [comment]
本项目可以正常使用gpt-4。用gpt-4-0613模型就行。

**Comment by Erimus-Koo** [comment]
好像直接指定GPT-4也行。
另外，请问怎么给GPT4发送图片和文档？

**Comment by wshze** [comment]
@Kerwin1202  大佬研究下gpt4官方新出的code interpreter 这个插件。非常牛逼啊。上传文件就可以给你排查问题，分析问题。不用一段一段贴代码去问gpt了。plus用户可以直接用

**Comment by 123Jason-cn** [comment]
@huangwb8 为什么我用GPT-4-0613提示这个报错？The model: gpt-4-0613 does not exist

**Comment by 123Jason-cn** [comment]
@Erimus-Koo 官网上说的这段话是什么意思？
![image](https://github.com/Kerwin1202/chatgpt-web/assets/75602210/ca08c629-c7d3-4150-bbf2-ae9d8d33a50a)

**Comment by jurieo** [comment]
> @Kerwin1202 大佬研究下gpt4官方新出的code interpreter 这个插件。非常牛逼啊。上传文件就可以给你排查问题，分析问题。不用一段一段贴代码去问gpt了。plus用户可以直接用

代码插件只有plus才有吧，api是没有的
