### ISSUE TITLE
现在GPT-4出来了。能否加上上传文件的功能？

### ISSUE THREAD

**Issue by 123Jason-cn** [chatgpt-web-dev/chatgpt-web#316]
现在Chat GPT-4出来了，能否加上文件上传的功能？？？？

**Comment by zhujunsan** [comment]
GPT-4 的api并没有处理文件/图片的能力

**Comment by wejudging** [comment]
> GPT-4 的api并没有处理文件/图片的能力

官网可以的

**Comment by wshze** [comment]
https://api.openai.com/v1/files
这个接口可以上传文件。然后调用OpenAI Embedding API 将数据向量化就可以了

**Comment by zhujunsan** [comment]
> https://api.openai.com/v1/files 这个接口可以上传文件。然后调用OpenAI Embedding API 将数据向量化就可以了

没看懂🤔，files 接口上传文件主要用在finetune上的吧？还有embedding接口怎么访问上传的文件啊？以及以及embedding只能对文本做向量化吧？以及以及以及，向量化完了拿这个向量接下来怎么再用在对话里面呢？

**Comment by BobDu** [comment]
#479
