### ISSUE TITLE
Docker Compose部署提示500，提示Topology is closed

### ISSUE THREAD

**Issue by tinnnnnnny** [chatgpt-web-dev/chatgpt-web#326]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/132983406/16f2ea11-87bd-450f-ba2c-ee782bbbcff1)
求助

**Comment by Urmi10799** [comment]
check your DB connection is accessible from your host machine.

**Comment by BobDu** [comment]
未正确配置 MONGODB_URL 导致。最新版本已优化该错误提示
