### ISSUE TITLE
这个支持多个acess Token吗？

### ISSUE THREAD

**Issue by 1205129045x** [chatgpt-web-dev/chatgpt-web#335]
我就是我添加多个acess Token，新建new chat可以自动选择可以用的acesstoken吗

**Comment by Kerwin1202** [comment]
首次发送随机选一个，后续固定这个，  如果删除了这个token 会导致无法对话

**Comment by Kerwin1202** [comment]
目前没有 后续会考虑，只能目前数据库看，而且标记的不是token，token 本身很长 是解析之后的账户 或者说邮箱之类的，要显示也是这个

**Comment by Kerwin1202** [comment]
是 accountId 然后 用你的 页面设置添加 key 的地方 去拿到 accesstoken 倒下面这个网址去解析 也有一个类似的 user- 之类的 一样就是

https://www.box3.cn/tools/jwt.html
