### ISSUE TITLE
部署提示500，提示Topology is closed

### ISSUE THREAD

**Issue by ytanck** [chatgpt-web-dev/chatgpt-web#368]
部署提示500，提示Topology is closed

如果没有MONGODB_URL项目是不是启动不了

**Comment by Kerwin1202** [comment]
是啊，这个项目必须要有的。不然没办法服务器保存数据

**Comment by ytking** [comment]
> 是啊，这个项目必须要有的。不然没办法服务器保存数据

支持mysql吗

**Comment by Kerwin1202** [comment]
> > 是啊，这个项目必须要有的。不然没办法服务器保存数据
> 
> 支持mysql吗

不支持
