### ISSUE TITLE
图片上传和图片显示功能是该加了吧?

### ISSUE THREAD

**Issue by padixa** [chatgpt-web-dev/chatgpt-web#377]
HTML显示个图片, 或者上传个图片又不是什么难事儿. 加一下呗.

**Comment by Kerwin1202** [comment]
麻烦的不是这，是 这个项目原来调用底层其他的库， 其他人的库 很久没更新

**Comment by assassinliujie** [comment]
> 麻烦的不是这，是 这个项目原来调用底层其他的库， 其他人的库 很久没更新

我看了眼文档，直接传图片链接也行。
所以如果底层调用对图片有啥问题的话，打包个图床自动返回图片链接其实也行

**Comment by assassinliujie** [comment]
import OpenAI from "openai";

const openai = new OpenAI();

async function main() {
  const response = await openai.chat.completions.create({
    model: "gpt-4-vision-preview",
    messages: [
      {
        role: "user",
        content: [
          { type: "text", text: "What’s in this image?" },
          {
            type: "image_url",
            image_url: {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
            },
          },
        ],
      },
    ],
  });
  console.log(response.choices[0]);
}
main();

**Comment by assassinliujie** [comment]
我现在写了一点点就是加了个上传图片按钮，上传到图床里自动返回链接，然后配上图片描述的文字框。
但是还没想好如果要把输入框整合到原来那里该怎么弄

**Comment by assassinliujie** [comment]
目前想了想干脆就用提示词，比如
img[https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg]
这样就不需要改前端了，后端处理掉就好了

**Comment by BobDu** [comment]
#479
