### ISSUE TITLE
ChatGPT error 429:  It is recommended to upgrade to the latest PandoraNext  用不了了，求救！

### ISSUE THREAD

**Issue by NiuHK** [chatgpt-web-dev/chatgpt-web#380]
报错：ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}

![image](https://github.com/Kerwin1202/chatgpt-web/assets/129147116/2cef2aff-30a8-4767-9724-8f7a9a11297b)

**Comment by NiuHK** [comment]
不是，我后来查了一下是默认的反向代理有问题，有人在别的地方提过类似的issue，解决办法是自己部署反代
:https://github.com/Chanzhaoyu/chatgpt-web/issues/1973

**Comment by Kerwin1202** [comment]
看了下，那我这也干不了啥呀，最多去找个 免费的反向代理 然后把默认的换掉。。这和你自己去找个反向代理 填写到设置界面也是一样的再或者就你发的这个 自己部署个也行

<img width="789" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/138eb43f-978c-47f6-b920-a21170f78fc6">

**Comment by huangwb8** [comment]
@NiuHK  

自建代理就行，比如[linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)这个项目。具体见《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。虽然[linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)已经不再更新，该有的功能应该都写好了，其中可以凑合着用的。最后直接加到“反向代理”这一栏即可：
![image](https://github.com/Kerwin1202/chatgpt-web/assets/35643122/68944abd-f3e2-4559-b23d-4aa5604cee12)
祝好！

**Comment by xiaoguaishou92** [comment]
> @NiuHK
> 
> 自建代理就行，比如[linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)这个项目。具体见《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。虽然[linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)已经不再更新，该有的功能应该都写好了，可以凑合着用。最后直接加到“反向代理”这一栏即可： ![image](https://private-user-images.githubusercontent.com/35643122/287870125-68944abd-f3e2-4559-b23d-4aa5604cee12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDI2NzUsIm5iZiI6MTcwODI0MjM3NSwicGF0aCI6Ii8zNTY0MzEyMi8yODc4NzAxMjUtNjg5NDRhYmQtZjNlMi00NTU5LWIyM2QtNGFhNTYwNGNlZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA3NDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NjU4YWVlZjljOWU1NmI1ZTJjNzk1YTFkYWRhYzNiODdkZTA0ZjkzMjY1M2FkNzIxOTc1ZDMxOGUxNjE1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nnTArNrFtBdBGIEExPQD6hzWN8GtyNk2ku9Hm6xnd54) 祝好！

这个好像也不能用了，有没有其他的呢

**Comment by NiuHK** [comment]
那天看了基本上都不行了，pandora以前有公开的但上次我看也不行了
