### ISSUE TITLE
回复经常会卡住，使用 gpt-4 时很严重（ 使用API )

### ISSUE THREAD

**Issue by Alfred-Windsor** [chatgpt-web-dev/chatgpt-web#382]
![1](https://github.com/Kerwin1202/chatgpt-web/assets/152876591/56b19747-8d35-4fd8-99bd-f970d2932412)

就像图里面似的

![2](https://github.com/Kerwin1202/chatgpt-web/assets/152876591/57c0e259-3a81-44fd-a6ef-8c062a718060)

监控了下网络发现是这个一直在请求（/api/chat-process），而且此时打开设置会发现在转圈加载，所有项都在加载。

使用的是 API 接口，我配置了百度云的敏感词审核，和这个有关系吗？

**Comment by Kerwin1202** [comment]
审核没关系默认是输入审核，输出代码没处理。。
打开设置选项是会加载的 每个tab都加载一次接口，以前会加载使用量访问openai接口会慢，但是后来去掉了，应该不慢。得看看你机器啥是否ok

卡主这个 你要么试试官网是否正常，说不好是代理有问题

**Comment by Cyrus-Reed-US** [comment]
> 审核没关系默认是输入审核，输出代码没处理。。 打开设置选项是会加载的 每个tab都加载一次接口，以前会加载使用量访问openai接口会慢，但是后来去掉了，应该不慢。得看看你机器啥是否ok
> 
> 卡主这个 你要么试试官网是否正常，说不好是代理有问题

感谢您回复我，我在等待您回复的期间试着把敏感词审核关闭了，居然再也没出现过这种问题。。不过按您说的好像和这个关系不大，我也不知道为啥，不过现在已经能够正常使用了，谢谢您！
