### ISSUE TITLE
困惑，ChatGPT error 429

### ISSUE THREAD

**Issue by yefeiyu** [chatgpt-web-dev/chatgpt-web#393]
我新安装的。安装后在设置-Key管理里也填写api了。怎么就不行呢。
我是买的官方的plus，特地在“基本配置-接口地址”中又填了[https://api.openai.com也不行。](https://api.openai.xn--com-928drof48z./)
错误提示如下。可是我官网地址是正常使用的。

ChatGPT error 429: {
"error": {
"message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}

**Comment by Kerwin1202** [comment]
在官网用 和你 配置 api key 模式是不一样的，官网是 免费 无额度限制的， apikey 是有额度的，  你要配置 access token 模式

**Comment by yefeiyu** [comment]
> 在官网用 和你 配置 api key 模式是不一样的，官网是 免费 无额度限制的， apikey 是有额度的， 你要配置 access token 模式

确实access token 模式是可以的。但是如何使用kerwin的这个项目上使用？我在配置文件docker-compose.yml中设置了，还是不管用。我记得最早去年的时候，是直接在yml文件中设置。现在是不是chatgpt-web这个项目都改成在gui客户端的“设置”中设置？但是在设置中我没有找到相关设置access token的地方。
请明示

**Comment by Kerwin1202** [comment]
@yefeiyu 

<img width="457" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/41639d9e-2e62-45bc-aa3c-9233cacdee84">
<img width="231" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/f1dfb593-f2f6-4b76-a53d-7257a3a70b22">
<img width="837" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/a23e74f1-7a75-40f8-bb35-5caaa7876dc6">

**Comment by yefeiyu** [comment]
还得麻烦你一次：
按上面填写后，使用时提示：ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}
导引到另一个GitHub上了。

**Comment by Kerwin1202** [comment]
https://github.com/Kerwin1202/chatgpt-web/issues/380

参考这个issue 下面其他人的回复
