### ISSUE TITLE
【求助】关于500错误

### ISSUE THREAD

**Issue by nankaine** [chatgpt-web-dev/chatgpt-web#418]
首先，感谢维护这个工具。

目前我自己测试了一个，使用docker部署了`kerwin1202/chatgpt-web` 、`mongo`。 并设置了nginx反向代理。 起初一切都正常。

但是在今天，在edeg 121.0.2277.83 (正式版本) (64 位)（火狐测试也有类似的情况）中，由于登录账号后长时间没有做操作，当我再次使用的时候，无法输入内容。 就关闭网页后重新开启，就会一直跳转到`https://atest.xyz:8443/#/500`,然后网页就一直报500错误了,和[官方演示站](https://chatgpt-web-kappa-inky.vercel.app/#/500)。有点类似
类似于这个图
![](https://private-user-images.githubusercontent.com/29082840/301057836-1a49122f-a71a-452f-8f02-e1ba8b0c99fc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYxMDEsIm5iZiI6MTcwNjY5NTgwMSwicGF0aCI6Ii8yOTA4Mjg0MC8zMDEwNTc4MzYtMWE0OTEyMmYtYTcxYS00NTJmLThmMDItZTFiYThiMGM5OWZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZWMxMzE2YTlhNmQ5OWU1NjMwMmE3NmY4Zjc1NmU5YzVhN2ZlMTFkMDE2Y2ZlYzVlMGZhMjdjNTBlZjcwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-dxmnMLD81grgjQaGvWqxgQgvAjUk-oEhjxwLPl9-64)

点击 go to home. 网页无跳转
![](https://p9-feedback-sign.byteimg.com/tos-cn-i-0000c0797/37dc61b0812747e9b03b223a3f529590~tplv-nztq419xn5-image.image?rk3s=336f70e4&x-expires=1706700379&x-signature=y6BC4chU1xXl4SnzssxnECn1GB0%3D)

但是我另外使用edge再单独开一个隐身模式，就可以正常到登录界面并登录进去。

部分nginx配置文件
尝试过 `http://127.0.0.1:3002`和`http://127.0.0.1:3002/`
```
gzip off;
location / {    
        proxy_pass http://127.0.0.1:3002/;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
    }
```

```
    gzip off;
    location / {    
        proxy_pass http://127.0.0.1:3002/;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_cache off;
        proxy_cache_bypass $http_pragma;
        proxy_cache_revalidate on;
        proxy_http_version 1.1;
        proxy_buffering off;
    }
```

目前这2个都测试了，都会出现一直跳转到500错误界面。

查询nginx的请求日志
```
测试IP - - [31/Jan/2024:18:22:32 +0800] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:32 +0800] "GET /assets/index-05b70042.js HTTP/1.1" 304 0 "https://atest.xyz:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:32 +0800] "GET /assets/index-7eba6e11.css HTTP/1.1" 304 0 "https://atest.xyz:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:33 +0800] "POST /api/session HTTP/1.1" 200 89 "https://atest.xyz:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:33 +0800] "POST /api/session HTTP/1.1" 200 89 "https://atest.xyz:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:33 +0800] "GET /assets/index-453fb3b1.js HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
测试IP - - [31/Jan/2024:18:22:33 +0800] "GET /assets/_plugin-vue_export-helper-c27b6911.js HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
```

最后，感谢维护这个工具。

**Comment by qsirwyk** [comment]
试试清理本地浏览器缓存再刷新 或者  换个浏览器试试 看看是不是缓存引起的错误

**Comment by Kerwin1202** [comment]
应该没关系，后面我把提示输出一下，然后这样可以docker log 看到
