### ISSUE TITLE
最新代码热更新失败

### ISSUE THREAD

**Issue by 193099** [chatgpt-web-dev/chatgpt-web#424]
最新代码拉下来后热更新不起作用,开启了vite.config.ts下的server的hmr后也不会热更新

**Comment by BobDu** [comment]
@193099 能提供一下具体哪些文件修改后无法触发 hmr 吗? 我测试了一些文件修改都是可以正常触发 hmr 的。
辛苦提供一下更具体的复现步骤。

**Comment by BobDu** [comment]
fixed in #470
