### ISSUE TITLE
不能调用github copilot的GPT4

### ISSUE THREAD

**Issue by zhenkuaileya** [chatgpt-web-dev/chatgpt-web#426]
用github copilot的API接入这个平台，他回答他不是GPT4。接入其它平台没这个问题

**Comment by InternetBugs** [comment]
所以为什么不问它“鲁迅为什么暴打周树人”
老版本gpt4模型本来就不认得自己是谁
copilot转为api的项目里写的很清楚了，鉴别是否为gpt4的方法就是问“鲁迅为什么暴打周树人”，而非让它说自己是gpt4

**Comment by InternetBugs** [comment]
模型本身并不认识自己是谁
其他平台应该是在Prompt里告诉了模型他是gpt4
你看看log就懂了
azure得gpt4照样说自己是gpt3
