### ISSUE TITLE
每次升级后之前设置的"角色设定"会被重置

### ISSUE THREAD

**Issue by padixa** [chatgpt-web-dev/chatgpt-web#429]
能否在数据库某个地方存一下每个用户之前保存的角色设定? 不然每次升级后都会被重置掉, 真的很麻烦.

**Comment by xiaoguaishou92** [comment]
是不是你的数据库版本问题，我用最新版本的MongoDB没有问题

**Comment by padixa** [comment]
@xiaoguaishou92  一直用: monodb:4.0, 并没有用latest.  但每次更新后其他参数都在, 只是所有用户角色设置变成默认的:"You are the Chatgpt...".

**Comment by xiaoguaishou92** [comment]
> @xiaoguaishou92 一直用: monodb:4.0, 并没有用latest. 但每次更新后其他参数都在, 只是所有用户角色设置变成默认的:"You are the Chatgpt...".
换一下试试吧，那个太老了，我用新版没有问题

**Comment by padixa** [comment]
@xiaoguaishou92 你用哪个版本?  这种问题和数据库版本有关? 不应该吧....

**Comment by xiaoguaishou92** [comment]
> @xiaoguaishou92 你用哪个版本? 这种问题和数据库版本有关? 不应该吧....

我用的latest，最新版本，好像是6.x，确实跟版本有问题，我之前低版本也有些莫名其妙的问题，换了就好了

**Comment by padixa** [comment]
@xiaoguaishou92 好久前我用过latest,结果出了问题就换回4.0的,从那以后固定用4.0....看来我还是需要抽时间升级下. 多谢哈.

**Comment by padixa** [comment]
升级到7.0了. 目前更新没发现什么大问题.
