### ISSUE TITLE
禁用"可提问次数"功能

### ISSUE THREAD

**Issue by yxguy** [chatgpt-web-dev/chatgpt-web#435]
用于个人使用，最新更新后增加了“可提问次数”功能，虽然可以把这个数设得很大，但有点强迫症，看得可用数不断减少，心里不舒服，怎么禁用它，例如设为0或者设为-1等，就可以不使用这个数

**Comment by BobDu** [comment]
ping @ccjaread 是否可以再来一个PR将该功能配置为可选的?

**Comment by zhaobudaomingzi** [comment]
> ping @ccjaread 是否可以再来一个PR将该功能配置为可选的?

你好，请问怎么禁用该功能配置？
