### ISSUE TITLE
更新 feat: add usage limit code后出现错误

### ISSUE THREAD

**Issue by richsense** [chatgpt-web-dev/chatgpt-web#436]
出现  错误 :  auth middleware getUserId err from token undefined  Cannot read properties of undefined (reading 'replace')

**Comment by richsense** [comment]
尝试完全重新 fork和deploy 后错误依然出现

**Comment by BobDu** [comment]
Use no login mode?

**Comment by BobDu** [comment]
@ccjaread 看起来可能是破坏了单用户非登录模式下的使用。是否可以协助排查一下呢?

**Comment by Urmi10799** [comment]
> Use no login mode?

No. while using login mode this error happens. Suppose I already logged into account and then logout, this error throws at console shows error 500 page. Another is while trying to access localhost:3002 , it throws error and shows error 500 page. Only works if user is already logged in.
