### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by 02000823** [chatgpt-web-dev/chatgpt-web#437]
我的电脑屏幕为16.1英寸，在使用时会显示不完全
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/84962546/e4648b9f-861d-4190-b360-8daac9828e8a)

**Comment by xiaoguaishou92** [comment]
14寸 1080p的笔记本也是一样的情况

**Comment by null0034** [comment]
这个fork代码后能自己改一下min-width或者width就行，屏幕太小的缘故，不影响使用

**Comment by BobDu** [comment]
该问题应该是由屏幕大小和分辨率设置导致的。但是我没有相同大小的设备用于复现验证。 
希望有条件的童鞋可以帮助修复一下贡献个PR
