### ISSUE TITLE
在使用coze-discord-proxy作为代理产生了一些问题

### ISSUE THREAD

**Issue by CiZaii** [chatgpt-web-dev/chatgpt-web#441]
在使用coze-discord-proxy做代理之后，先是在chatgpt-next-web中，配置了自定义接口，和api-key之后请求key正常，但是在使用这个过程中，不知道是配置错误还是，代码逻辑层面有问题，发送的请求是get请求导致404
<img width="1496" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/71380295/87b30335-f62a-4c6f-b5ee-dbc0f798bbbc">
<img width="1284" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/71380295/3b506034-a12b-49d7-89e6-161dcbc3ab90">
next-web中的配置如下
<img width="991" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/71380295/38a5eeed-de64-4608-9348-8ecc68162598">

项目的docker-compose配置如下
app:
    # 在https://hub.docker.com/r/kerwin1202/chatgpt-web/tags 里获得tag。或者写latest
        image: kerwin1202/chatgpt-web:main
        restart: unless-stopped
        ports:
            - 3002:3002
        depends_on:
            - database
        environment:
            TZ: Asia/Shanghai
      # 从OpenAI后台里获得
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
            AUTH_SECRET_KEY: cls108 # 按需修改
      # 超时，单位毫秒，可选
            TIMEOUT_MS: 60000
      # 网站名
            SITE_TITLE: cffyChat # 按需修改。写个自己喜欢的名字就行
      # mongodb 的连接字符串
            MONGODB_URL: 'mongodb://user01:password01@database:27017' # 按需修改
      # 网站是否开启注册
            REGISTER_ENABLED: "true" # 完成注册后，这一项要改为false
      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
            REGISTER_MAILS: '@qq.com,@gmail.com,@163.com' # 按需修改
      # 加密盐。算法： echo -n 'passwordsalt' | md5sum | cut -c 1-32
            PASSWORD_MD5_SALT: tNJ%M&D # 按需修改
      # 开启注册之后 超级管理员的邮箱
            ROOT_USER: 2556450572@qq.com # 按需修改
      # 开启注册之后网站域名 不含 / 。注册的时候发送验证邮箱使用
      # SITE_DOMAIN: https://172.16.0.114:8084 # 按需修改
      # 开启注册之后 发送验证邮箱配置
      # SMTP_HOST: smtp.qq.com
      # SMTP_PORT: 465
      # SMTP_TSL: true
      # SMTP_USERNAME: 724247159@qq.com # 按需修改
      # SMTP_PASSWORD: xxxxxxxx # 按需修改
        links:
            - database
            
            本人能力有限排查无果，期待可以解决

**Comment by ZangJuxy** [comment]
补充，代理端日志
<img width="1319" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/71380295/fdabd97a-1c51-49a4-bc13-47d59c7579e5">
