### ISSUE TITLE
docker部署报错500，但是可以跳转

### ISSUE THREAD

**Issue by fangjuncao** [chatgpt-web-dev/chatgpt-web#447]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/86115575/893d4971-1353-4075-8066-6fa6309eedff)

容器日志如下
Server is running on port 3002
auth middleware getUserId err from token undefined  Cannot read properties of undefined (reading 'replace')
auth middleware getUserId err from token undefined  Cannot read properties of undefined (reading 'replace')

**Comment by ywk94** [comment]
这个bug一直没人修

**Comment by Kerwin1202** [comment]
如果还会的话，提供下 下面两个截图里  请求头  request header  主要是 Authorization 这个属性 ，目前服务器 发现这个数据读取不到，所以会报错

<img width="650" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/16319833/cefe649b-fc14-4603-80d6-8b6a8961ebc5">

<img width="765" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/16319833/12c76a56-71a4-4884-bfbe-399a9ad80a6d">

**Comment by fangjuncao** [comment]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/86115575/ad04a384-4f39-44af-b5b0-bd371bc6eca2)
![223d6dde9b0342d7991162854d0351fc](https://github.com/chatgpt-web-dev/chatgpt-web/assets/86115575/e6460f84-c1a5-4ad6-ac53-d9081ca6ed7a)
请查看，谢谢

**Comment by fangjuncao** [comment]
[image: 223d6dde9b0342d7991162854d0351fc.png]
[image: 223d6dde9b0342d7991162854d0351fc.png]
请查看，谢谢

Kerwin1202 ***@***.***> 于2024年3月2日周六 17:28写道：

**Comment by m0eak** [comment]
> ![image](https://private-user-images.githubusercontent.com/86115575/309469022-ad04a384-4f39-44af-b5b0-bd371bc6eca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzUxMDUsIm5iZiI6MTcwOTQ3NDgwNSwicGF0aCI6Ii84NjExNTU3NS8zMDk0NjkwMjItYWQwNGEzODQtNGYzOS00NGFmLWI1YjAtYmQzNzFiYzZlY2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE0MDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiM2YzYTUxOWUyZjJmZjE2ODE1ZjFmYzVhZDg2MTQ5ZDFhNTg2YzljZGQ1YjRlNThhY2UxMmUyOTY4MWFkODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRjEat-d-c1xKaCVkSzLG-pD1ZYEKQ6aP2Hy2eDlr-c) ![223d6dde9b0342d7991162854d0351fc](https://private-user-images.githubusercontent.com/86115575/309469033-e6460f84-c1a5-4ad6-ac53-d9081ca6ed7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzUxMDUsIm5iZiI6MTcwOTQ3NDgwNSwicGF0aCI6Ii84NjExNTU3NS8zMDk0NjkwMzMtZTY0NjBmODQtYzFhNS00YWQ2LWFjNTMtZDkwODFjYTZlZDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE0MDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmN2MyYjNhNjQyMDY5YTViMjI4MGVhZWNlODJjYjZlNDc5MTliYTgwYWUwZmNkMWU5YTk3YTc3NWJjMGU2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdWspN8r3OJ1bfhmuxDiyV3sSrId4p5L1UkPCwdsUFg) 请查看，谢谢

我拉了最新的还是报这个错，日志里也没有报错

**Comment by BobDu** [comment]
> 我拉了最新的还是报这个错，日志里也没有报错

辛苦点击5xx页面的 `Go to Home` 按钮。应该是能回到主页。

看一下主页左下角使用的版本号。 

<img width="343" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/20370175/3ed24b60-9f66-490f-98a0-e05f3ad7dd5f">

---

最新的版本。 跳转500并且日志这个报错基本确定是成功修复了。
```
auth middleware getUserId err from token undefined Cannot read properties of undefined (reading 'replace')
```

怀疑还是没有拉到最新的镜像。执行命令确保成功拉到了最新的镜像。

```
docker pull kerwin1202/chatgpt-web
docker pull chatgptweb/chatgpt-web
```

**Comment by m0eak** [comment]
> > 我拉了最新的还是报这个错，日志里也没有报错
> 
> 辛苦点击5xx页面的 `Go to Home` 按钮。应该是能回到主页。
> 
> 看一下主页左下角使用的版本号。
> 
> <img alt="image" width="343" src="https://private-user-images.githubusercontent.com/20370175/309566479-3ed24b60-9f66-490f-98a0-e05f3ad7dd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTgwNTQsIm5iZiI6MTcwOTUxNzc1NCwicGF0aCI6Ii8yMDM3MDE3NS8zMDk1NjY0NzktM2VkMjRiNjAtOWY2Ni00OTBmLTk4YTAtZTA1ZjNhZDdkZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAyMDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOTdkNGE0ZDNmMDNmNDI1NTcxYTQ5NGRmY2VlNDhlYjdhMTAwMmE2MDZhNDg5YmQ3NjhkYjBlMDI0ZTE3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IuMqjE2xE4vxdLUbA8tIPB4w0emqZ_E8ULlniE3882c">
> 最新的版本。 跳转500并且日志这个报错基本确定是成功修复了。
> 
> ```
> auth middleware getUserId err from token undefined Cannot read properties of undefined (reading 'replace')
> ```
> 
> 怀疑还是没有拉到最新的镜像。执行命令确保成功拉到了最新的镜像。
> 
> ```
> docker pull kerwin1202/chatgpt-web
> docker pull chatgptweb/chatgpt-web
> ```

进去了，但是直接就是聊天界面了，没有注册什么的，这个正常吗，，dockercompose里开启注册写的也是true

**Comment by wenhaodudragonplus** [comment]
> 进去了，但是直接就是聊天界面了，没有注册什么的，这个正常吗，，dockercompose里开启注册写的也是true

`AUTH_SECRET_KEY` 有设置吗?

**Comment by BobDu** [comment]
> 进去了，但是直接就是聊天界面了，没有注册什么的，这个正常吗，，dockercompose里开启注册写的也是true

`AUTH_SECRET_KEY` 有设置吗?

**Comment by m0eak** [comment]
> > 进去了，但是直接就是聊天界面了，没有注册什么的，这个正常吗，，dockercompose里开启注册写的也是true
> 
> `AUTH_SECRET_KEY` 有设置吗?

好了，谢谢
