### ISSUE TITLE
【需求】加个弹窗或通知窗口

### ISSUE THREAD

**Issue by Yang2635** [chatgpt-web-dev/chatgpt-web#463]
网站每次模型接入的变化都无法更好有效的通知到使用的人，希望可以增加一个弹窗/通知窗口，方便有些模型变动或网站的更新等能以弹窗/通知的形式使得其它使用者了解到其改动。

**Comment by BobDu** [comment]
很好的一个想法。有大佬愿意帮助提供一个PR来实现一下吗?

**Comment by Han-Zhong** [comment]
> 网站每次模型接入的变化都无法更好有效的通知到使用的人，希望可以增加一个弹窗/通知窗口，方便有些模型变动或网站的更新等能以弹窗/通知的形式使得其它使用者了解到其改动。

支持这个想法！希望大佬们可以帮助实现一下🫡salute
