### ISSUE TITLE
Unable to access settings via cloudflared tunnel. Able to access user settings via local host.

### ISSUE THREAD

**Issue by spencerwongfeilong** [chatgpt-web-dev/chatgpt-web#469]
Hello,

After updating to version 2.15.0, I am facing an issue where I cannot access the user settings menu through a cloudflared tunnel. The menu does not pop up as expected.

However, I can successfully access the user settings menu when using my network IP address followed by the port number.

Do I need to adjust or add any specific configurations to resolve this issue?

**Comment by BobDu** [comment]
Can you open browser devtools and see network tab?
Maybe some request is failed.
If you could investigate from this angle and provide more information, it would help with problem-solving.

**Comment by spencerwongfeilong** [comment]
> Can you open browser devtools and see network tab? Maybe some request is failed. If you could investigate from this angle and provide more information, it would help with problem-solving.

Hello i resolved it by ending the following variables in the docker compose. 
      VITE_APP_API_BASE_URL: xxx.yyy.win
      VITE_GLOB_OPEN_LONG_REPLY: true
      HTTPS_PROXY: xxx.yyy.win
      VITE_GLOB_APP_PWA: true  (this doesnt seem to enable PWA)
