### ISSUE TITLE
pnpm build 前端出错

### ISSUE THREAD

**Issue by yilong789** [chatgpt-web-dev/chatgpt-web#473]
![QQ截图20240310143826](https://github.com/chatgpt-web-dev/chatgpt-web/assets/122464513/4905deed-a19e-4ce6-8c40-575dbc2b2476)

**Comment by BobDu** [comment]
我没能复线出来唉。是什么原因啊？ 有全局安装的依赖干扰了吗？ 还是没有pnpm install啊？
@yilong789

**Comment by yilong789** [comment]
是bootstrap 忘记安装了
