### ISSUE TITLE
环境设置ROOT_USER为自己的邮箱，登录提示账户状态异常

### ISSUE THREAD

**Issue by wp861010** [chatgpt-web-dev/chatgpt-web#475]
环境设置ROOT_USER为自己的邮箱，使用此邮箱注册之后登录提示账户状态异常，什么问题？

**Comment by MAOUXSAKI** [comment]
应该是新增代码导致的bug, 可以先手动去mongodb的gui，把用户status手动改成0就可以了

**Comment by dqzboy** [comment]
同+1
<img width="344" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/42825450/5366154c-4490-4baf-aeac-b970416a9a59">

**Comment by MAOUXSAKI** [comment]
service\src\storage\mongo.ts
export async function createUser(email: string, password: string, roles?: UserRole[], status?: Status, remark?: string, useAmount?: number, limit_switch?: boolean): Promise<UserInfo> {
  email = email.toLowerCase()
  const userInfo = new UserInfo(email, password)
  if (roles && roles.includes(UserRole.Admin))
    userInfo.status = Status.Normal
  if (status !== null)
    userInfo.status = status

  userInfo.roles = roles
  userInfo.remark = remark
  userInfo.useAmount = useAmount
  userInfo.limit_switch = limit_switch
  await userCol.insertOne(userInfo)
  return userInfo
}

这个方法错了，if (status !== null)，在创建管理员账号的时候，status没有传，status在这里是undefined，双不等号必须要完全不等才算不等，改成!=就可以了

**Comment by BobDu** [comment]
> 这个方法错了，if (status !== null)，在创建管理员账号的时候，status没有传，status在这里是undefined，双不等号必须要完全不等才算不等，改成!=就可以了

一直没来得及看 感谢感谢。提个PR?
