### ISSUE TITLE
已更新到2.16,无法画图

### ISSUE THREAD

**Issue by zxczhai** [chatgpt-web-dev/chatgpt-web#483]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/89773545/31525eca-ead2-4845-9b52-eb1417e48794)
如图,选择了gpt4-vision-preview,但是没有图片生成

**Comment by InternetBugs** [comment]
vision只是识图模型，画图模型是dall-e
ai跟你说他能画图你别真信

**Comment by BobDu** [comment]
> vision只是识图模型

+1
