### ISSUE TITLE
smtp发送邮件成功了，但是邮箱厂商把a标签地址修改了，导致打不开，怎么解决？

### ISSUE THREAD

**Issue by PopcornEdward** [chatgpt-web-dev/chatgpt-web#484]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/130227817/cb05406a-b7aa-4620-9f8a-c5e74e5a62b6)
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/130227817/5561cfad-581c-4085-8c19-aa878cbf406b)

**Comment by BobDu** [comment]
那把a标签改成p标签让它不能点只能手动复制? 不确定会不会好一些。

**Comment by BobDu** [comment]
或者你是不是设置 `site domain` 的时候没有加 `https://` 前缀啊?

**Comment by MoonS11** [comment]
请问您的asstoken模式可以使用吗
