### ISSUE TITLE
能否录个简单的开发环境搭建视频教程?

### ISSUE THREAD

**Issue by padixa** [chatgpt-web-dev/chatgpt-web#486]
比如下载源码后用VS Code怎么调试(安装哪些必要扩展, 环境)....咱也学一下搭建环境并如何开发调试. 有什么小功能开发一下, 也贡献一些.

**Comment by BobDu** [comment]
能力不足。讲不来。
但是欢迎大佬们录制和本项目相关的教学视频哈。视频发布后可以在项目README上加个链接。
