### ISSUE TITLE
怎么只有三个模型了

### ISSUE THREAD

**Issue by isen121** [chatgpt-web-dev/chatgpt-web#489]
![de427e6e61c0605d690575c281b56e4](https://github.com/chatgpt-web-dev/chatgpt-web/assets/134914963/c3759195-154c-4468-9972-d305a8feb3e2)

**Comment by BobDu** [comment]
新的部署初始化配置文件时默认只有这三个常用模型。其他自定义模型可以在网站设置中自行添加。
