### ISSUE TITLE
希望可以添加自定义模型名称，不需要每次新增模型都要作者来更新

### ISSUE THREAD

**Issue by JeazW** [chatgpt-web-dev/chatgpt-web#494]
我的API支持claude, 可是选项里没有，只能在API聚合平台那边把请求过来的gpt-4-vision-preview模型映射成claude

**Comment by yuntao1997** [comment]
设置-》网站设置-》基本模型，   有这个功能诶

**Comment by MoonS11** [comment]
请问您是使用access token模式部署成功还是 api key方式部署成功的

**Comment by JeazW** [comment]
> 请问您是使用access token模式部署成功还是 api key方式部署成功的

api key
另外access token那个接口目前好像是废的

**Comment by JeazW** [comment]
> 设置-》网站设置-》基本模型， 有这个功能诶

我的锅，感谢感谢😄

**Comment by MoonS11** [comment]
啊十分感谢解惑

**Comment by kahoch** [comment]
> > 设置-》网站设置-》基本模型， 有这个功能诶
> 
> 我的锅，感谢感谢😄


自己增加了claude，但是用不了。请问你是官方的api吗？
