### ISSUE TITLE
误修改超级管理员为user，无法恢复其超管身份

### ISSUE THREAD

**Issue by chilohwei** [chatgpt-web-dev/chatgpt-web#496]
不小心更改了超级管理员账号的身份为`user`，重新登录后，没有超级管理员的权限了，具体表现为设置项里没有邮箱、用户、Key等配置项了。

想请教这个是否支持在数据库里，通过修改字段来恢复超级管理员身份，如果可以的话，应该修改哪个字段？

**Comment by BobDu** [comment]
`user` 表里面找到要修改的用户。`roles` 数组字段中加一个 `0`
<img width="630" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/20370175/4719cd58-6b59-419f-8d93-6f811d49f926">

**Comment by chilohwei** [comment]
感谢，已解决。
