### ISSUE TITLE
哪位大佬愿意分享一下数据库表结构，不甚感激！！！

### ISSUE THREAD

**Issue by jiangxh18** [chatgpt-web-dev/chatgpt-web#498]

**Comment by BobDu** [comment]
看一下`model` 文件。数据库表都是通过这个文件中的类来定义的。
https://github.com/chatgpt-web-dev/chatgpt-web/blob/main/service/src/storage/model.ts

**Comment by jiangxh18** [comment]
@BobDu 感谢指点！！！我按照model建立数据表，运行程序出现的问题感觉有些奇怪，怀疑是由于数据或者数据表的问题。
作者为什么在项目里没有提供数据库构建说明呢？

**Comment by jiangxh18** [comment]
![无标题](https://github.com/chatgpt-web-dev/chatgpt-web/assets/128229867/752623df-dc03-4255-8f9b-f5a62222982f)

**Comment by BobDu** [comment]
> 作者为什么在项目里没有提供数据库构建说明呢？

MongoDB 本身就是非关系型数据库。无需提前建库建表 提前定义表结构的。

**Comment by jiangxh18** [comment]
@BobDu 多谢大佬指点！
