### ISSUE TITLE
使用 dall-e-3 模型，服务拒绝

### ISSUE THREAD

**Issue by helloknown** [chatgpt-web-dev/chatgpt-web#501]
部署最新版镜像，日志如下，同样的 API 使用 chatbox 时，选用 dall-e-3 绘画没有问题，帮忙看下什么问题，现在支持该模型吗
ChatGPTError: ChatGPT error 403: {"error":{"message":"You are not allowed to sample from this model (request id: 2024032314154219670177966dVNVyE) (request id: 2024032322153658662282408166570)","type":"invalid_request_error","param":"","code":null}}
    at fetchSSE (/app/node_modules/.pnpm/@chatgptweb+chatgpt-api@5.3.0/node_modules/@chatgptweb/chatgpt-api/src/fetch-sse.ts:27:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by BobDu** [comment]
目前还不支持 image generations 类型的模型
