### ISSUE TITLE
输出公式没有正常渲染

### ISSUE THREAD

**Issue by mitu752** [chatgpt-web-dev/chatgpt-web#504]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/59833868/a62f93b2-c099-4f9e-9e13-1c8f62e61cd6)

**Comment by BobDu** [comment]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/20370175/d8905015-07ac-4ab2-905f-8a532aae96a7)
页面渲染是支持的。只是LLM没有输出符合格式要求的内容。

调一下PE就行。
Role:
You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully.Respond using markdown.
=>
You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully.Respond using markdown (latex start with $).
