### ISSUE TITLE
最新版本【aaae763】的复制功能用不了，麻烦复原下原来的！！！

### ISSUE THREAD

**Issue by huangzt** [chatgpt-web-dev/chatgpt-web#530]

**Comment by BobDu** [comment]
我在 chrome 123 浏览器中测试复制按钮是可以正常工作的 
可以提供一些更多的信息以更好的解决这个问题吗?

**Comment by huangzt** [comment]
> 我在 chrome 123 浏览器中测试复制按钮是可以正常工作的 可以提供一些更多的信息以更好的解决这个问题吗?
我的是macbook pro m1
mac下都提示复制失败！
<img width="370" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/4033637/1b01df7b-7b7c-4ebb-923c-9c7231f270f3">
<img width="284" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/4033637/921162da-b1a3-4e36-8325-7ca8f53dff50">

Parallels Desktop 虚拟机win11，同样也是提示复制失败！
<img width="405" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/4033637/c4956392-3eeb-48e2-a4c6-aea61c1a3f96">
<img width="366" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/4033637/dfc8017f-d4e6-484c-9d16-97f57cfe1b2a">

这个js对象 navigator.clipboard 是 undefined

上面各个版本测试了，确实不行。可以让有macbook的同事帮忙测试下

**Comment by huangzt** [comment]
原来的代码这样改就可以了吧？可能是监听事件的问题！

export function copyToClip(text: string) {
  return new Promise((resolve, reject) => {
    try {
      const input: HTMLTextAreaElement = document.createElement('textarea')
      input.setAttribute('readonly', 'readonly')
      input.value = text?.replace(/\n+$/, '\n')
      document.body.appendChild(input)
      input.select()
      if (document.execCommand('copy'))
        document.execCommand('copy')
      document.body.removeChild(input)
      resolve(text)
    }
    catch (error) {
      reject(error)
    }
  })
}

**Comment by huangzt** [comment]
上面这样改测试没有问题的，仅供参考：
<img width="763" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/4033637/a6222b44-74fa-40e0-a39d-03eba8a8c4fa">

**Comment by BobDu** [comment]
应该是 你使用的 http 访问一个非localhost地址 导致的 navigator.clipboard api无法使用?
方便的话帮忙测试一下PR中的更改是否解决了这个问题?
ping @huangzt

**Comment by huangzt** [comment]
测试可以
@BobDu
