### ISSUE TITLE
4o模型没有图片输入吗

### ISSUE THREAD

**Issue by cjnss008** [chatgpt-web-dev/chatgpt-web#543]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/56506642/94b97396-ad41-4b38-a1c7-856def2f987a)

**Comment by BobDu** [comment]
看下左下角。用的哪个版本。

**Comment by BobDu** [comment]
更新一下。

**Comment by cjnss008** [comment]
> 更新一下。

谢谢，已解决
