### ISSUE TITLE
手工部署项目后500错误

### ISSUE THREAD

**Issue by jiangxh18** [chatgpt-web-dev/chatgpt-web#556]
请问大佬，在docker下，分别在mongo、nodejs、nginx容器中，按照手工方法复制service文件夹，build打包前端，.env文件中VITE_GLOB_API_URL=/api未修改，运行后报500错，请问哪个地方设置错误了？
![无标题](https://github.com/chatgpt-web-dev/chatgpt-web/assets/128229867/b6f091e3-3d2b-4153-b3f6-9de428584043)

**Comment by 1825679767** [comment]
老哥 我也是相同问题，前端后端都没有任何报错，但是就是进不去
