### ISSUE TITLE
OpenAI 对话模型丢失，只剩3个

### ISSUE THREAD

**Issue by jamesoujj** [chatgpt-web-dev/chatgpt-web#559]
大佬好，我是通过docker部署的，刚刚将image升级到最新，但是发现对话模型中只有三个，并且gpt-4-vision-preview在实际使用时提示模型不存在。
我修改了docker compose文件，增加了下面两个environment参数，但也没有起作用。
      OPENAI_API_MODEL: gpt-4o
      MODEL: gpt-4o

我是非常想用gpt-4o，还请支持哈，谢谢大佬
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/7608077/c2a847a0-4f7f-48bf-a424-97ac9eb78ea1)

**Comment by zhujunsan** [comment]
较新的版本部署的话，请在网站设置里自己设置想要用的模型，半角逗号分隔，保存后刷新页面，然后进行你上面说的配置

![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/839807/3f0bee8d-11a2-43f1-af2e-982666a65935)

**Comment by jamesoujj** [comment]
可以了，感谢
