### ISSUE TITLE
能否支持设置API对话的上下文条数

### ISSUE THREAD

**Issue by ixxmu** [chatgpt-web-dev/chatgpt-web#560]
没找到上下文条数的限制，因为用API对话的时候当上下文过长将极度耗费API额度，特别是用GPT4对话？
在issue里看到之前是支持设置的

**Comment by BobDu** [comment]
<img width="739" alt="image" src="https://github.com/chatgpt-web-dev/chatgpt-web/assets/20370175/38e091ba-beae-40cb-93ee-68d411c3d38c">
可以在这里设置

**Comment by ixxmu** [comment]
> <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/20370175/344373094-38e091ba-beae-40cb-93ee-68d411c3d38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTE2MTgsIm5iZiI6MTcxOTY1MTMxOCwicGF0aCI6Ii8yMDM3MDE3NS8zNDQzNzMwOTQtMzhlMDkxYmEtYmVhZS00MGNiLTkzZWUtNjhkNDExYzNkMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA4NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmUzYzhmMTljZjZkODI0M2Y3YWRiNmY4M2NlMmQyZGVkYjg2OTBjZWYyNjY4MDEzYTRiMThkYWI3ZTE1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uLkT1xp3bfvvzAl7-N6wQGlltslWkwwrLACBJ5JpIbE">
> 可以在这里设置

这需要每个用户在前端自行设置，能不能由管理员加一个最大数的限制，上下文过长太消耗API了；

查到issue历史里好像之前的版本是可以的

**Comment by BobDu** [comment]
![image](https://github.com/chatgpt-web-dev/chatgpt-web/assets/20370175/3b85e10b-1a89-48a9-877f-5898ba502ef7)

**Comment by ixxmu** [comment]
> ![image](https://private-user-images.githubusercontent.com/20370175/344383146-3b85e10b-1a89-48a9-877f-5898ba502ef7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzM3MjAsIm5iZiI6MTcxOTY3MzQyMCwicGF0aCI6Ii8yMDM3MDE3NS8zNDQzODMxNDYtM2I4NWUxMGItMWE4OS00OGE5LTg3N2YtNTg5OGJhNTAyZWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE1MDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDI2ZWZmNjZkZTc1MzQ0ZjViOGIzYTQxNzE2OTI0NzkwMGJhNTljNTkyNTYxNGM3YWQxM2FhZWYwMjA0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9C-4fnfSm9Ou-KgoQMXtTF_orkZG-8sQ4M1XbCgRe-s)

我用的老版本的mongo，所以没有高级选项，重新升级之后出现了，谢谢！
再次感谢佬这么棒的项目！
