### ISSUE TITLE
用oneApi转发的claude每三条必报错

### ISSUE THREAD

**Issue by ixxmu** [chatgpt-web-dev/chatgpt-web#564]
用oneApi转发的claude每三条必报错，报错信息如下
>ChatGPT error 400: {"error":{"message":"messages: first message must use the "user" role (request id: 2024081100154940271669176077206) (request id: 20240811001549284482743vT52aNSn)","type":"invalid_request_error","param":"","code":null}}.

但是在nextchat上没有这个问题

**Comment by BobDu** [comment]
fixed by: #588
