### ISSUE TITLE
Docker，数据库突然打不开了。

### ISSUE THREAD

**Issue by youzhazhu** [chatgpt-web-dev/chatgpt-web#96]
如题，原本正常使用，刚才发现网站进不去了
利用Docker Compose部署的
宝塔面板启动数据库容器失败
![image](https://user-images.githubusercontent.com/51223192/235290277-b3d5a25d-8ec6-4aaf-81c1-0fe249a62c0a.png)

**Comment by Kerwin1202** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/16319833/235299518-9f68462d-cf3f-4a8d-a371-312df47a1b9b.png">
